baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "A Blog"
theme = "lanyon-hugo"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/yeedle"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/yeedle"

[params]

 DateForm = "Mon Jan _2 15:04:05 2006"
    description = "pseudorandom thoughts and projects"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

